### ISSUE TITLE
Is there a way to add points efficiently to the clusters without rebuilding?

### ISSUE THREAD

**Issue by jpnathannew** [mapbox/supercluster#126] opened 2019-06-11 09:38 UTC
@mourner 
I am creating server side clustering with supercluster. is there any possible way to add points without rebuilding. I am building based on accountId and storing into array. It will be huge. Without rebuilding any other possible way to include the new point or update the existing point?
please guide me

**Comment by mourner** [comment] 2019-06-11 09:41
Not at the moment. Closing as duplicate of #19.

**Comment by jpnathannew** [comment] 2019-06-11 09:41
@mourner thanks for your response

**Closed by mourner** 2019-06-11 09:41 UTC

**Comment by spkostas** [comment] 2020-05-10 20:42
Hi ,do you have any updates on how to remake places.json and places-z0-0-0.json with different locations?
PS I'm failing to add about 8m pins on map , works well with under a million.
