### ISSUE TITLE
MinZoom clustering not working

### ISSUE THREAD

**Issue by noushad-pp** [mapbox/supercluster#44] opened 2017-04-03 14:00 UTC
i am passing minzoom as 3 to the superclusterer, but the clusterer is not clustering the item below the zoom level 6.

**Comment by mourner** [comment] 2017-04-13 18:34
Can you set up a minimal JSFiddle test case that reproduces this? I don't quite understand your issue.

**Comment by lbtuda** [comment] 2017-04-15 15:21
Same problem, when I am clustering points South hemisphere. In Northern hemisphere everything works.

at zoomlevels <6 everything works, when higher zoom levels are chosen, the points are not visible anymore. But the clustering algo returns them. so maybe the points are corrupt?

**Comment by mourner** [comment] 2017-04-15 16:10
@lbtuda same as above — would appreciate a minimal JSFiddle test case!

**Comment by lbtuda** [comment] 2017-04-15 16:42
Hi, here is an minimal test case:
[https://jsfiddle.net/3n840uwa/6/](https://jsfiddle.net/3n840uwa/6/)

On the northern hemisphere everything works as expected.
Note: you have to zoom with the mousewheel so the center of the maps changes.
Thank you :)

**Comment by mourner** [comment] 2017-08-29 14:53
> But the clustering algo returns them. so maybe the points are corrupt?

If supercluster returns them, I assume the issue is not on supercluster side. I'm closing the issue for now because I'm not able to reproduce. If you're still experiencing this, I'd appreciate a very minimal test example (without any frameworks, just supercluster and as few points as possible).

**Closed by mourner** 2017-08-29 14:53 UTC
Labels: question
