### ISSUE TITLE
How to run supercluster as server side clustering

### ISSUE THREAD

**Issue by jpnathannew** [mapbox/supercluster#124] opened 2019-05-23 10:16 UTC
I am creating server side clustering for my map. When I use PHP and Mysql for create the clustering it is taking more time. So I am planning to use this project
I have few doubts
> How to run this project as server?
> If I pass My lat and lang points into this project this will convert everything to cluster?
> How to expose API for markers to cluster?

Please help me. I am waiting for your response

**Comment by mourner** [comment] 2019-05-23 11:15
Duplicate of #79

**Closed by mourner** 2019-05-23 11:15 UTC

**Comment by jpnathannew** [comment] 2019-05-23 12:34
> Duplicate of #79

It is not a duplicate of #79. Please guide me to use this supercluster

**Comment by xlcrr** [comment] 2020-10-15 21:30
hi @jpnathannew did you make any progress? I am working on the same problem. Maybe we can help each other?

**Comment by kityan** [comment] 2020-10-16 11:17
hi @xlcrr! What is the problem you trying to solve? You can follow these steps with nodejs app:
- load points (lat, lng) from source (database, file, etc)
- convert data to a suitable format (GeoJSON Point) 
- build index with `new Supercluster(options).load(points)` 
When I was developing such application, I've wanted to store clusters, but the best solution was to serve directly from nodejs app using (see `getClusters` method).

**Comment by xlcrr** [comment] 2020-10-16 12:37
Hi @kityan thanks for the message

I am using Laravel PHP framework on the backend.

Once the client has the data, processing it with supercluster is incredibly fast (100's ms). The slowest part seems to be getting the data from the table into the browser (9-10s for 100,000 points and growing) therefore I need to save the metadata on a table and update this with a script on the backend.

I am still trying to figure out how to do this but I am thinking about passing the data into a javascript file and execute it on the backend with `$response = exec('node my_script.js')`, and store this data to a table to allow for faster lookup, or maybe using a microservice. (Both of which I am new to).

**Comment by kityan** [comment] 2020-10-16 13:02
@xlcrr the main idea is not to send 100k points to client for clusterization. For my project I have splitted front end code: for some zoom levels (e.g. 9-18) it requests backend for points (here you can use directly your php backend). For other zoom levels (e.g. 1-8) it requests backend for CLUSTERS not for POINTS. And here nodejs app with Supercluster comes in. You can proxy with web-server (nginx, etc) or via your php code. 
Of course loading 100k points from db may be slow, but it will be done rarely. You nodejs app (with Supercluster) should do this operation (rebuild index) on some events in db: e.g. point add, point remove, point update. So, you need to make some kind of communication between your php code (here are methods for point add/remove/update) and nodejs app. Or if you use MongoDB or any other db with `watch` features, you can place such watchers directly in nodejs app (handler function will get all points again and rebuild index)

**Comment by kityan** [comment] 2020-10-16 13:08
@xlcrr My advice: do not store clusters index to db (I am not really sure that Supercluster's index is serializable). 
Build a standalone microservice using nodejs+Supercluster and let it store and rebuild clusters index in memory. 
You will be able easily request this microservice to give clusters for BBox (see `getClusters` method)
Yes, you should be familiar with long-live server side (nodejs vs php). But it's worth it.

**Comment by xlcrr** [comment] 2020-10-16 19:56
@kityan thank you very much for the reply. I will do some research and report back

**Comment by xlcrr** [comment] 2020-10-21 21:47
@kityan I decided to save zoom levels to DB

see https://openlittermap.com/global :-)

**Comment by kityan** [comment] 2020-10-22 11:39
@xlcrr, well done! I don't think that it's the best solution (to store clusters to DB and not to serve them from standalone app), especially if you have to reindex clusters frequently. But, anyway. My backend is always nodejs, so it's more convenient to me.
P.S. I've remembered your project from angel.co, we've chatted there. If you will need any advice on my stack (see the link in github profile) — let me know.

**Comment by kityan** [comment] 2020-10-22 11:54
@xlcrr P.S. A little more about pros and cons. When I use standalone app to handle frontend requests I can use `getClusterExpansionZoom()` to improve UX. I recieve bbox and zoom level from frontend. Then I get clusters with `getClusters()` and then patch data with info from `getClusterExpansionZoom()` for each cluster. Also you can decrease response size. GeoJSON is a bit verbose and if you communicate only with your own frontend, you can simplify json.
But I think you can patch data also before storing in database. Anyway, as a result you can make clusters clickable (to zoom when the cluster expands). It's much more user friendly.

**Comment by xlcrr** [comment] 2020-10-24 22:10
@kityan I have recently launched OpenLitterMap as open source. You can see my backend PHP implementation [here](https://github.com/OpenLitterMap/openlittermap-web/blob/master/app/Console/Commands/Clusters/GenerateClusters.php). Can't believe we chatted before that's great! Sounds like an awesome implementation, well done! We will see what the emerging OLM community can recommend as refactoring this atm is currently outside my timeframe

**Comment by yudeqang** [comment] 2023-08-30 08:57
Have any postgis implementation verstion?

**Comment by rivalthreatening9** [comment] 2025-02-03 16:10
I see the light https://preprocessor.space/questions/banning-the-use-of-server-side-rendering-advantages-and-disadvantages
