### ISSUE TITLE
Can't render more than 100 markers

### ISSUE THREAD

**Issue by cassio-nuke** [mapbox/supercluster#108] opened 2018-11-21 15:26 UTC
Hello,

We are having a issue and I am not sure why.
I can't render more than 115 markers.
If it's 114 it renders perfectly. More than that it renders nothing.

Can you please give some advice?

Thanks in advance.

**Comment by mourner** [comment] 2018-11-21 15:42
I have to close this because there's no information that would help me identify the issue. Please provide a minimal reproducible test case.

**Closed by mourner** 2018-11-21 15:42 UTC
